- name: Read GRE tunnel settings
  include_vars:
    file: "{{ role_path }}/config/{{ inventory_hostname }}.yml"
  ignore_errors: true

- name: Enumerate GRE tunnels to update
  set_fact:
    _gre_to_add: "{{ gre_peers | default([]) | selectattr('remove', 'false') | list
                    + gre_peers | default([]) | selectattr('remove', 'undefined') | list}}"

- name: Write updated GRE tunnels
  include_tasks: "gre-update.yml"
